platform :ios, '12.2'

use_frameworks!

target 'SignalRingRTC' do
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git', testspecs: ["Tests"]
  pod 'WebRTCForTesting', path: '../../../out/'
end

target 'SignalRingRTCTests' do
  pod 'SignalCoreKit', git: 'https://github.com/signalapp/SignalCoreKit.git', testspecs: ["Tests"]
  pod 'Nimble', '~> 9.0'
end
