#!/bin/sh

#
# Copyright 2019-2021 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

# Be sure to install the specific nightly toolchain:
# rustup toolchain install nightly-2020-03-15

cargo +nightly-2020-03-15 fmt "$@"
