#!/bin/sh

#
# Copyright (C) 2019, 2020 Signal Messenger, LLC.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-only
#

OUTPUT_DIR="${OUTPUT_DIR:-/tmp/ringrtc-tests}"
export RANDOM_SEED="${RANDOM_SEED:-$(date +%s)}"
cargo test --features sim --target-dir=$OUTPUT_DIR "$@" -- --nocapture --test-threads=1
